input {
  file {
    path => "/home/madhura/Desktop/KernelShield/elk/security_logs.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

output {
  elasticsearch {
    hosts => ["https://localhost:9200"]
    user => "elastic"
    password => "rgk1ocv_J1lE-3J8FCaM"
    ssl_enabled => true
    ssl_verification_mode => "none"
    index => "kernelshield-logs"
  }

  stdout {
    codec => rubydebug
  }
}
