#ifndef KERNELSHIELD_EVENT_H
#define KERNELSHIELD_EVENT_H

#include <linux/types.h>

#define KS_COMM_LEN 16
#define KS_FILENAME_LEN 256

/* Event categories generated by KernelShield */
enum ks_event_type {
    KS_EVENT_PROCESS_EXEC = 1,
    KS_EVENT_NETWORK_CONNECT,
    KS_EVENT_PRIVILEGE_CHANGE
};

/*
 * Common event structure exchanged between
 * eBPF programs and userspace.
 */
struct ks_event {

    /* Timestamp in nanoseconds */
    __u64 timestamp_ns;

    /* Process Information */
    __u32 pid;
    __u32 ppid;
    __u32 uid;
    __u32 gid;

    /* Event category */
    __u32 type;

    /* Executable name */
    char comm[KS_COMM_LEN];

    /* Full executable path (future use) */
    char filename[KS_FILENAME_LEN];
};

#endif
