#ifndef EVENT_H
#define EVENT_H

#include <linux/types.h>

#define TASK_COMM_LEN 16

/* Types of events generated by KernelShield */
enum event_type {
    EVENT_PROCESS_EXEC = 1,
    EVENT_NETWORK_CONNECT,
    EVENT_PRIVILEGE_CHANGE
};

/* Common event structure shared across the project */
struct event {
    __u64 timestamp_ns;              // Event timestamp
    __u32 pid;                       // Process ID
    __u32 ppid;                      // Parent Process ID
    __u32 uid;                       // User ID
    enum event_type type;            // Event type
    char comm[TASK_COMM_LEN];        // Process name
};

#endif /* EVENT_H */
